18 produire des masques à partir de la seule analyse de limage
InseeFrLab/detection-habitat-spontane pull request #28
Opened 2023-04-03 15:04 UTC by rayaberova7

Ajout de fonctions dans plot_utils.
Création d'image_utils.
Création des notebooks masque infra pour développer les fonctions et expliquer ainsi que test masque infra pour tester ces fonctions une fois implémentées dans le code source.

2023-04-03 18:34 UTC, rayaberova7 commented
> Ajout de fonctions dans plot_utils. Création d'image_utils. Création des notebooks masque infra pour développer les fonctions et expliquer ainsi que test masque infra pour tester ces fonctions une fois implémentées dans le code source. Réécriture du fichier environnement (surtout les données pléiade)

2023-04-07 15:59 UTC, tomseimandi requested changes
Super ces fonctions ! Des remarques mineures avec une remarque globale. Le fait que je fasse plusieurs fois les mêmes commentaires suggère qu'il y a beaucoup de code dupliqué ce qui ne facilite pas la maintenance. Peut-être que ça vaudrait le coup de créer des petites fonctions à la place du code répliqué ? Par exemple une fonction qui split un filename Pleiades et renvoie le département et l'année, que tu pourrais appeler dans toutes tes fonctions. Dis-moi en tous cas si des choses ne sont pas claires on peut faire un Zoom pour en parler !

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +from mappings import *
Détail mais en général on a envie d'éviter les imports généraux avec *

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +        GPS coordinate : latitude and logitutude.
"longitude"

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +        folder_path = '../data/PLEIADES/' + str((satellite_image.date).year) + '/' + num_dep_to_name_dep[satellite_image.dep]
détail mais est-ce que ça ne serait pas logique d'aller chercher ça dans `environment.yml` ?
style `environment["local-path"]["PLEIADES"][str((satellite_image.date).year)][num_dep_to_name_dep[satellite_image.dep]]` à qques détails près (utile comme ça si on change environment.yml y'aura ça pourrait éviter des pb

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +    Gives the gps point of the left-top boundingbox of the image. Argument is either a SatelliteImage or a filepath.
Il faut peut-être spécifier que pour l'instant ça marche vraiment avec les images Pleiades qu'on a, la méthode est basée sur les noms de fichiers.

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +def gps_to_crs_point(lat : float, lon : float, crs : int or str) :
détail mais `int or str` -> `Union[int, str]`

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +        pattern = "|".join(delimiter)
pattern c'est juste "/" ici non du coup ?

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +    pattern = "|".join(delimiters)
pattern c'est juste "/" ici non du coup ?

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +def find_image_of_point(coordinate : list, folder_path : str, coord_gps = False) :
`coordinates` au pluriel ? + détail mais le type hint c'est `List` plutôt que `list`

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +        folder_path = '../data/PLEIADES/' + str((satellite_image.date).year) + '/' + num_dep_to_name_dep[satellite_image.dep]
Même commentaire qu'au-dessus

2023-04-07 15:59 UTC, tomseimandi commented on src/image_utils.py
> +    pattern = "|".join(delimiter)
Cf. au-dessus

2023-04-07 15:59 UTC, tomseimandi commented on src/plot_utils.py
> +        satellite_image.plot([0,1,2])
Ce code doit faire ce qu'on veut mais on pourrait faire plus simple je pense + là on fait des modifs sur satellite_image donné en input ce qu'on veut peut-être éviter de faire. 

Une bonne méthode ici je dirais serait de créer un array white et un array black de la taille de l'image avec `np.zeros` et `np.ones` + de créer le mask avec `np.where`. Dis-moi ce que tu en penses !

2023-04-07 15:59 UTC, tomseimandi commented on src/plot_utils.py
> +                        img[row, col] = np.array([255,255,255,255]) # noir
Même remarque que la fonction précédente + peut-être qu'au lieu de répliquer le code tu pourrais appeler la fonction précédente justement ?

2023-04-07 15:59 UTC, tomseimandi commented on src/plot_utils.py
> +                    img[row, col] = [255,255,255,255] # blanc
Même remarque que précédemment sur la modification de l'input de la fonction

2023-04-07 15:59 UTC, tomseimandi commented on src/plot_utils.py
> +        folder_path = '../data/PLEIADES/' + str((satellite_image.date).year) + '/' + num_dep_to_name_dep[satellite_image.dep]
environment.yml cf au dessus

2023-04-07 15:59 UTC, tomseimandi commented on src/plot_utils.py
> +    pattern = "|".join(delimiter)
Mm remarque qu'au dessus

2023-04-11 12:27 UTC, rayaberova7 commented
> 

Merci beaucoup pour tes retours, ça me fait bien progresser !

2023-04-11 18:22 UTC, rayaberova7 commented on src/image_utils.py
> +    pattern = "|".join(delimiters)
oui exact !!

2023-04-13 19:54 UTC, rayaberova7 commented on src/plot_utils.py
> +        satellite_image.plot([0,1,2])
effectivement c'est mieux, j'ai tout repris !

2023-04-14 16:25 UTC, tomseimandi commented
@rayaberova7 je te laisse "squash and merge" quand tu veux, et comme commit message tu peux résumer tout ce qui est fait dans la branche rapidement !

2023-04-14 20:30 UTC, merged